class Commands:
    LEECH = "leech@LeechV2_Bot"
    PURGE = "purge@LeechV2_Bot"
    PAUSEALL = "pauseall@LeechV2_Bot"
    RESUMEALL = "resumeall@LeechV2_Bot"
    STATUS = "status@LeechV2_Bot"
    SETTINGS = "settings@LeechV2_Bot"
    EXEC = "exec@LeechV2_Bot"
    UPLOAD = "upload@LeechV2_Bot"
    YTDL = "ytdl@LeechV2_Bot"
    PYTDL = "pytdl@LeechV2_Bot"
    ABOUT = "about@LeechV2_Bot"
    GETLOGS = "getlogs@LeechV2_Bot"
    SERVER = "server@LeechV2_Bot"
    USERSETTINGS = "usetting@LeechV2_Bot"
    INSTADL = "instadl@LeechV2_Bot"
